services:
  web_server1:
    image: 0xtr1gger/nginx_load_balancer:web_server1
    container_name: web_server1
    ports:
      - "5001:5001"
    networks:
      - nginx-network

  web_server2:
    image: 0xtr1gger/nginx_load_balancer:web_server2
    container_name: web_server2
    ports:
      - "5002:5002"
    networks:
      - nginx-network

  nginx_load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge